[mcp_servers.supabase-fv]
url = "https://mcp.supabase.com/mcp?project_ref=bfmaqrythlwbfjuqumom&features=docs%2Caccount%2Cdatabase%2Cdebugging%2Cdevelopment%2Cfunctions%2Cbranching"

[mcp_servers.supabase-elite]
url = "https://mcp.supabase.com/mcp?project_ref=lzowflvgnspjdbvdxliy&features=docs%2Caccount%2Cdatabase%2Cdebugging%2Cdevelopment%2Cfunctions%2Cbranching"
